// Generated from api.quran.com/api/v4/chapters — static Quran metadata, never changes.
// [name_simple, name_arabic, verses_count, english_meaning]
export const SURAHS = [
  ["Al-Fatihah", "الفاتحة", 7, "The Opener"],
  ["Al-Baqarah", "البقرة", 286, "The Cow"],
  ["Ali 'Imran", "آل عمران", 200, "Family of Imran"],
  ["An-Nisa", "النساء", 176, "The Women"],
  ["Al-Ma'idah", "المائدة", 120, "The Table Spread"],
  ["Al-An'am", "الأنعام", 165, "The Cattle"],
  ["Al-A'raf", "الأعراف", 206, "The Heights"],
  ["Al-Anfal", "الأنفال", 75, "The Spoils of War"],
  ["At-Tawbah", "التوبة", 129, "The Repentance"],
  ["Yunus", "يونس", 109, "Jonah"],
  ["Hud", "هود", 123, "Hud"],
  ["Yusuf", "يوسف", 111, "Joseph"],
  ["Ar-Ra'd", "الرعد", 43, "The Thunder"],
  ["Ibrahim", "ابراهيم", 52, "Abraham"],
  ["Al-Hijr", "الحجر", 99, "The Rocky Tract"],
  ["An-Nahl", "النحل", 128, "The Bee"],
  ["Al-Isra", "الإسراء", 111, "The Night Journey"],
  ["Al-Kahf", "الكهف", 110, "The Cave"],
  ["Maryam", "مريم", 98, "Mary"],
  ["Taha", "طه", 135, "Ta-Ha"],
  ["Al-Anbya", "الأنبياء", 112, "The Prophets"],
  ["Al-Hajj", "الحج", 78, "The Pilgrimage"],
  ["Al-Mu'minun", "المؤمنون", 118, "The Believers"],
  ["An-Nur", "النور", 64, "The Light"],
  ["Al-Furqan", "الفرقان", 77, "The Criterion"],
  ["Ash-Shu'ara", "الشعراء", 227, "The Poets"],
  ["An-Naml", "النمل", 93, "The Ant"],
  ["Al-Qasas", "القصص", 88, "The Stories"],
  ["Al-'Ankabut", "العنكبوت", 69, "The Spider"],
  ["Ar-Rum", "الروم", 60, "The Romans"],
  ["Luqman", "لقمان", 34, "Luqman"],
  ["As-Sajdah", "السجدة", 30, "The Prostration"],
  ["Al-Ahzab", "الأحزاب", 73, "The Combined Forces"],
  ["Saba", "سبإ", 54, "Sheba"],
  ["Fatir", "فاطر", 45, "Originator"],
  ["Ya-Sin", "يس", 83, "Ya Sin"],
  ["As-Saffat", "الصافات", 182, "Those who set the Ranks"],
  ["Sad", "ص", 88, "The Letter \"Saad\""],
  ["Az-Zumar", "الزمر", 75, "The Troops"],
  ["Ghafir", "غافر", 85, "The Forgiver"],
  ["Fussilat", "فصلت", 54, "Explained in Detail"],
  ["Ash-Shuraa", "الشورى", 53, "The Consultation"],
  ["Az-Zukhruf", "الزخرف", 89, "The Ornaments of Gold"],
  ["Ad-Dukhan", "الدخان", 59, "The Smoke"],
  ["Al-Jathiyah", "الجاثية", 37, "The Crouching"],
  ["Al-Ahqaf", "الأحقاف", 35, "The Wind-Curved Sandhills"],
  ["Muhammad", "محمد", 38, "Muhammad"],
  ["Al-Fath", "الفتح", 29, "The Victory"],
  ["Al-Hujurat", "الحجرات", 18, "The Rooms"],
  ["Qaf", "ق", 45, "The Letter \"Qaf\""],
  ["Adh-Dhariyat", "الذاريات", 60, "The Winnowing Winds"],
  ["At-Tur", "الطور", 49, "The Mount"],
  ["An-Najm", "النجم", 62, "The Star"],
  ["Al-Qamar", "القمر", 55, "The Moon"],
  ["Ar-Rahman", "الرحمن", 78, "The Beneficent"],
  ["Al-Waqi'ah", "الواقعة", 96, "The Inevitable"],
  ["Al-Hadid", "الحديد", 29, "The Iron"],
  ["Al-Mujadila", "المجادلة", 22, "The Pleading Woman"],
  ["Al-Hashr", "الحشر", 24, "The Exile"],
  ["Al-Mumtahanah", "الممتحنة", 13, "She that is to be examined"],
  ["As-Saf", "الصف", 14, "The Ranks"],
  ["Al-Jumu'ah", "الجمعة", 11, "The Congregation, Friday"],
  ["Al-Munafiqun", "المنافقون", 11, "The Hypocrites"],
  ["At-Taghabun", "التغابن", 18, "The Mutual Disillusion"],
  ["At-Talaq", "الطلاق", 12, "The Divorce"],
  ["At-Tahrim", "التحريم", 12, "The Prohibition"],
  ["Al-Mulk", "الملك", 30, "The Sovereignty"],
  ["Al-Qalam", "القلم", 52, "The Pen"],
  ["Al-Haqqah", "الحاقة", 52, "The Reality"],
  ["Al-Ma'arij", "المعارج", 44, "The Ascending Stairways"],
  ["Nuh", "نوح", 28, "Noah"],
  ["Al-Jinn", "الجن", 28, "The Jinn"],
  ["Al-Muzzammil", "المزمل", 20, "The Enshrouded One"],
  ["Al-Muddaththir", "المدثر", 56, "The Cloaked One"],
  ["Al-Qiyamah", "القيامة", 40, "The Resurrection"],
  ["Al-Insan", "الانسان", 31, "The Man"],
  ["Al-Mursalat", "المرسلات", 50, "The Emissaries"],
  ["An-Naba", "النبإ", 40, "The Tidings"],
  ["An-Nazi'at", "النازعات", 46, "Those who drag forth"],
  ["'Abasa", "عبس", 42, "He Frowned"],
  ["At-Takwir", "التكوير", 29, "The Overthrowing"],
  ["Al-Infitar", "الإنفطار", 19, "The Cleaving"],
  ["Al-Mutaffifin", "المطففين", 36, "The Defrauding"],
  ["Al-Inshiqaq", "الإنشقاق", 25, "The Sundering"],
  ["Al-Buruj", "البروج", 22, "The Mansions of the Stars"],
  ["At-Tariq", "الطارق", 17, "The Nightcommer"],
  ["Al-A'la", "الأعلى", 19, "The Most High"],
  ["Al-Ghashiyah", "الغاشية", 26, "The Overwhelming"],
  ["Al-Fajr", "الفجر", 30, "The Dawn"],
  ["Al-Balad", "البلد", 20, "The City"],
  ["Ash-Shams", "الشمس", 15, "The Sun"],
  ["Al-Layl", "الليل", 21, "The Night"],
  ["Ad-Duhaa", "الضحى", 11, "The Morning Hours"],
  ["Ash-Sharh", "الشرح", 8, "The Relief"],
  ["At-Tin", "التين", 8, "The Fig"],
  ["Al-'Alaq", "العلق", 19, "The Clot"],
  ["Al-Qadr", "القدر", 5, "The Power"],
  ["Al-Bayyinah", "البينة", 8, "The Clear Proof"],
  ["Az-Zalzalah", "الزلزلة", 8, "The Earthquake"],
  ["Al-'Adiyat", "العاديات", 11, "The Courser"],
  ["Al-Qari'ah", "القارعة", 11, "The Calamity"],
  ["At-Takathur", "التكاثر", 8, "The Rivalry in world increase"],
  ["Al-'Asr", "العصر", 3, "The Declining Day"],
  ["Al-Humazah", "الهمزة", 9, "The Traducer"],
  ["Al-Fil", "الفيل", 5, "The Elephant"],
  ["Quraysh", "قريش", 4, "Quraysh"],
  ["Al-Ma'un", "الماعون", 7, "The Small kindnesses"],
  ["Al-Kawthar", "الكوثر", 3, "The Abundance"],
  ["Al-Kafirun", "الكافرون", 6, "The Disbelievers"],
  ["An-Nasr", "النصر", 3, "The Divine Support"],
  ["Al-Masad", "المسد", 5, "The Palm Fiber"],
  ["Al-Ikhlas", "الإخلاص", 4, "The Sincerity"],
  ["Al-Falaq", "الفلق", 5, "The Daybreak"],
  ["An-Nas", "الناس", 6, "Mankind"],
];

export const surahName = (n) => SURAHS[n - 1][0];
export const ayahCount = (n) => SURAHS[n - 1][2];
